-- Generated by scripts/generate-seed.mjs from assets/js/demo-data.js.
-- Do not hand-edit — rerun the generator instead.
--
-- Not applied automatically. Apply explicitly, once, after 0001_init.sql:
--   npx wrangler d1 execute <db-name> --file=./migrations/seed.sql --remote

INSERT OR IGNORE INTO authors (id, email, name, bio, avatar_key, role, created_at) VALUES ('a1', 'grant@mysite.com', 'Grant Cameron', 'Builds things on the edge. Writes about what broke.', NULL, 'owner', '2026-07-26T18:01:44Z');
INSERT OR IGNORE INTO authors (id, email, name, bio, avatar_key, role, created_at) VALUES ('a2', 'ada@mysite.com', 'Ada Okafor', 'Design systems, accessibility, and the occasional performance rant.', NULL, 'editor', '2026-07-26T18:01:44Z');

INSERT OR IGNORE INTO tags (id, slug, name, description) VALUES ('cloudflare', 'cloudflare', 'Cloudflare', NULL);
INSERT OR IGNORE INTO tags (id, slug, name, description) VALUES ('workers', 'workers', 'Workers', NULL);
INSERT OR IGNORE INTO tags (id, slug, name, description) VALUES ('d1', 'd1', 'D1', NULL);
INSERT OR IGNORE INTO tags (id, slug, name, description) VALUES ('r2', 'r2', 'R2', NULL);
INSERT OR IGNORE INTO tags (id, slug, name, description) VALUES ('mcp', 'mcp', 'MCP', NULL);
INSERT OR IGNORE INTO tags (id, slug, name, description) VALUES ('architecture', 'architecture', 'Architecture', NULL);
INSERT OR IGNORE INTO tags (id, slug, name, description) VALUES ('performance', 'performance', 'Performance', NULL);
INSERT OR IGNORE INTO tags (id, slug, name, description) VALUES ('accessibility', 'accessibility', 'Accessibility', NULL);
INSERT OR IGNORE INTO tags (id, slug, name, description) VALUES ('design', 'design', 'Design', NULL);

INSERT OR IGNORE INTO posts (id, slug, title, subtitle, excerpt, body_md, body_html, status, visibility, author_id, cover_key, cover_alt, word_count, reading_minutes, created_at, updated_at, published_at, scheduled_for) VALUES ('p1', 'shipping-a-blog-on-cloudflare-workers', 'Shipping a blog on Cloudflare Workers', 'One deployment, two hostnames, zero servers', 'Most blog engines start from the content model. This one started from the deployment topology, because the topology is what makes the security properties easy or hard, and everything else…', 'Most blog engines start from the content model. This one started from the
deployment topology, because the topology is what makes the security properties easy or
hard, and everything else follows from it.

## Two hostnames, one Worker

The whole thing is a single Worker bound to two custom domains:

- `blog.mysite.com` — public, anonymous, cached hard
- `blog-admin.mysite.com` — behind Cloudflare Access, never cached

The Worker''s first act is to look at `URL.hostname` and decide which world it is in.
On the public host, `/admin/*` and `/api/admin/*` return `404` unconditionally — not
`401`, not `403`. There is nothing to probe.

```js
export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const isAdmin = url.hostname === env.ADMIN_HOST;

    if (!isAdmin && ADMIN_PREFIXES.some((p) => url.pathname.startsWith(p))) {
      return new Response(''Not found'', { status: 404 });
    }
    return isAdmin ? handleAdmin(request, env, ctx) : handlePublic(request, env, ctx);
  },
};
```

## Why not a path prefix

Serving the editor from `blog.mysite.com/admin` would have been less DNS work. It also
would have made authorization a property of application code — one routing bug away from
publishing everyone''s drafts.

> Put the boundary somewhere a mistake in your code cannot move it.

With a separate hostname, Access terminates unauthenticated requests at the edge, before
the Worker runs at all. The public hostname does not have an admin surface to protect
because it does not have one at all.

## What it costs

One extra DNS record and one Access application. That is the entire price, and in
exchange the highest-severity failure mode in the system becomes a deployment
misconfiguration you can test for in one `curl`, rather than a code path you have to
keep getting right forever.', '<p>Most blog engines start from the content model. This one started from the
deployment topology, because the topology is what makes the security properties easy or
hard, and everything else follows from it.</p>
<h2 id="two-hostnames-one-worker">Two hostnames, one Worker</h2>
<p>The whole thing is a single Worker bound to two custom domains:</p>
<ul><li><code>blog.mysite.com</code> — public, anonymous, cached hard</li><li><code>blog-admin.mysite.com</code> — behind Cloudflare Access, never cached</li></ul>
<p>The Worker&#39;s first act is to look at <code>URL.hostname</code> and decide which world it is in.
On the public host, <code>/admin/*</code> and <code>/api/admin/*</code> return <code>404</code> unconditionally — not
<code>401</code>, not <code>403</code>. There is nothing to probe.</p>
<pre><code class="language-js">export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const isAdmin = url.hostname === env.ADMIN_HOST;

    if (!isAdmin &amp;&amp; ADMIN_PREFIXES.some((p) =&gt; url.pathname.startsWith(p))) {
      return new Response(&#39;Not found&#39;, { status: 404 });
    }
    return isAdmin ? handleAdmin(request, env, ctx) : handlePublic(request, env, ctx);
  },
};</code></pre>
<h2 id="why-not-a-path-prefix">Why not a path prefix</h2>
<p>Serving the editor from <code>blog.mysite.com/admin</code> would have been less DNS work. It also
would have made authorization a property of application code — one routing bug away from
publishing everyone&#39;s drafts.</p>
<blockquote><p>Put the boundary somewhere a mistake in your code cannot move it.</p></blockquote>
<p>With a separate hostname, Access terminates unauthenticated requests at the edge, before
the Worker runs at all. The public hostname does not have an admin surface to protect
because it does not have one at all.</p>
<h2 id="what-it-costs">What it costs</h2>
<p>One extra DNS record and one Access application. That is the entire price, and in
exchange the highest-severity failure mode in the system becomes a deployment
misconfiguration you can test for in one <code>curl</code>, rather than a code path you have to
keep getting right forever.</p>', 'published', 'public', 'a1', NULL, NULL, 224, 1, '2026-07-20T11:12:00Z', '2026-07-20T11:12:00Z', '2026-07-18T09:00:00Z', NULL);
INSERT OR IGNORE INTO post_tags (post_id, tag_id) VALUES ('p1', 'cloudflare');
INSERT OR IGNORE INTO post_tags (post_id, tag_id) VALUES ('p1', 'workers');
INSERT OR IGNORE INTO post_tags (post_id, tag_id) VALUES ('p1', 'architecture');

INSERT OR IGNORE INTO posts (id, slug, title, subtitle, excerpt, body_md, body_html, status, visibility, author_id, cover_key, cover_alt, word_count, reading_minutes, created_at, updated_at, published_at, scheduled_for) VALUES ('p2', 'designing-an-mcp-surface-for-content-editing', 'Designing an MCP surface for content editing', 'What an agent should and should not be able to do', 'Giving a model write access to a blog is easy. Giving it write access you can still sleep next to takes a bit more thought. Publishing is always its own call The single most useful…', 'Giving a model write access to a blog is easy. Giving it write access you can
still sleep next to takes a bit more thought.

## Publishing is always its own call

The single most useful constraint in the whole tool surface: `create_post` cannot
publish. Neither can `update_post`. The `status` field is ignored on write and forced
to `draft`.

That means an agent cannot make something live as a *side effect* of anything. Going
public requires calling a tool named `publish_post`, which is a decision, not an
accident. If the model gets a draft badly wrong, the blast radius is a draft.

## Tools are filtered by role

The MCP endpoint runs behind the same Cloudflare Access application as the admin UI, and
resolves the caller to the same `authors` row with the same role. An `author`-role
identity does not merely get rejected when it calls `publish_post` — it never sees
`publish_post` in `tools/list` at all.

| Role | Sees drafting tools | Sees publish/delete | Sees settings |
| --- | :---: | :---: | :---: |
| owner | yes | yes | yes |
| editor | yes | yes | no |
| author | yes | no | no |

Advertising a tool that will fail is a bad experience for a model in exactly the way it
is for a person: it will keep trying.

## Errors have to be actionable

A model recovers from a good error and flails at a vague one. Every failure returns a
stable `code`, the offending field, and where possible a fix:

```json
{
  "error": {
    "code": "slug_taken",
    "message": "A post with the slug \"edge-caching\" already exists.",
    "field": "slug",
    "suggestion": "edge-caching-2"
  }
}
```

That one `suggestion` field turns a round trip to the human into a retry.', '<p>Giving a model write access to a blog is easy. Giving it write access you can
still sleep next to takes a bit more thought.</p>
<h2 id="publishing-is-always-its-own-call">Publishing is always its own call</h2>
<p>The single most useful constraint in the whole tool surface: <code>create_post</code> cannot
publish. Neither can <code>update_post</code>. The <code>status</code> field is ignored on write and forced
to <code>draft</code>.</p>
<p>That means an agent cannot make something live as a <em>side effect</em> of anything. Going
public requires calling a tool named <code>publish_post</code>, which is a decision, not an
accident. If the model gets a draft badly wrong, the blast radius is a draft.</p>
<h2 id="tools-are-filtered-by-role">Tools are filtered by role</h2>
<p>The MCP endpoint runs behind the same Cloudflare Access application as the admin UI, and
resolves the caller to the same <code>authors</code> row with the same role. An <code>author</code>-role
identity does not merely get rejected when it calls <code>publish_post</code> — it never sees
<code>publish_post</code> in <code>tools/list</code> at all.</p>
<table><thead><tr><th>Role</th><th style="text-align:center">Sees drafting tools</th><th style="text-align:center">Sees publish/delete</th><th style="text-align:center">Sees settings</th></tr></thead><tbody><tr><td>owner</td><td style="text-align:center">yes</td><td style="text-align:center">yes</td><td style="text-align:center">yes</td></tr><tr><td>editor</td><td style="text-align:center">yes</td><td style="text-align:center">yes</td><td style="text-align:center">no</td></tr><tr><td>author</td><td style="text-align:center">yes</td><td style="text-align:center">no</td><td style="text-align:center">no</td></tr></tbody></table>
<p>Advertising a tool that will fail is a bad experience for a model in exactly the way it
is for a person: it will keep trying.</p>
<h2 id="errors-have-to-be-actionable">Errors have to be actionable</h2>
<p>A model recovers from a good error and flails at a vague one. Every failure returns a
stable <code>code</code>, the offending field, and where possible a fix:</p>
<pre><code class="language-json">{
  &quot;error&quot;: {
    &quot;code&quot;: &quot;slug_taken&quot;,
    &quot;message&quot;: &quot;A post with the slug \&quot;edge-caching\&quot; already exists.&quot;,
    &quot;field&quot;: &quot;slug&quot;,
    &quot;suggestion&quot;: &quot;edge-caching-2&quot;
  }
}</code></pre>
<p>That one <code>suggestion</code> field turns a round trip to the human into a retry.</p>', 'published', 'public', 'a1', NULL, NULL, 268, 2, '2026-07-11T14:30:00Z', '2026-07-11T14:30:00Z', '2026-07-11T14:30:00Z', NULL);
INSERT OR IGNORE INTO post_tags (post_id, tag_id) VALUES ('p2', 'mcp');
INSERT OR IGNORE INTO post_tags (post_id, tag_id) VALUES ('p2', 'architecture');

INSERT OR IGNORE INTO posts (id, slug, title, subtitle, excerpt, body_md, body_html, status, visibility, author_id, cover_key, cover_alt, word_count, reading_minutes, created_at, updated_at, published_at, scheduled_for) VALUES ('p3', 'd1-as-a-content-store', 'D1 as a content store: what worked, what surprised me', 'SQLite at the edge, holding actual prose', 'A blog is a small dataset with a demanding read pattern: a handful of queries, run constantly, that must be fast everywhere. That is a good fit for D1, with a few things worth knowing up…', 'A blog is a small dataset with a demanding read pattern: a handful of
queries, run constantly, that must be fast everywhere. That is a good fit for D1, with a
few things worth knowing up front.

## Markdown is the source of truth, HTML is a cache

Every post stores both `body_md` and `body_html`. Rendering happens once, on write.

The temptation is to render on read and keep one column. Don''t. Rendering on read puts a
Markdown parser on the hot path of every page view to produce a byte-identical result
every time. Rendering on write means a public read is one indexed `SELECT` and a
serialisation, and a change to the renderer becomes a migration — which is the right
place for it, because you want to know exactly when every post''s HTML changed.

## Store timestamps as ISO-8601 strings

Not epoch integers. They sort lexicographically, they are unambiguous about timezone, and
when you are staring at the D1 console at 2am trying to work out why a scheduled post did
not go out, you can read them.

## Set `published_at` exactly once

Editing a published post touches `updated_at` and nothing else. Unpublishing and
republishing does not reset it either. Otherwise a typo fix silently moves a two-year-old
post to the top of the feed and into every subscriber''s reader.

## The scheduled-publish query is free

```sql
CREATE INDEX idx_posts_scheduled ON posts(status, scheduled_for)
  WHERE status = ''scheduled'';
```

A partial index over the handful of scheduled rows. The cron trigger runs every five
minutes and the query touches almost nothing.

## What surprised me

Full-text search. `fts5` is available and works, but keeping the external-content table
in sync through triggers is more machinery than a personal blog needs. `LIKE` over title
and excerpt is genuinely fine below a few thousand posts, and you can add FTS the day
that stops being true.', '<p>A blog is a small dataset with a demanding read pattern: a handful of
queries, run constantly, that must be fast everywhere. That is a good fit for D1, with a
few things worth knowing up front.</p>
<h2 id="markdown-is-the-source-of-truth-html-is-a-cache">Markdown is the source of truth, HTML is a cache</h2>
<p>Every post stores both <code>body_md</code> and <code>body_html</code>. Rendering happens once, on write.</p>
<p>The temptation is to render on read and keep one column. Don&#39;t. Rendering on read puts a
Markdown parser on the hot path of every page view to produce a byte-identical result
every time. Rendering on write means a public read is one indexed <code>SELECT</code> and a
serialisation, and a change to the renderer becomes a migration — which is the right
place for it, because you want to know exactly when every post&#39;s HTML changed.</p>
<h2 id="store-timestamps-as-iso-8601-strings">Store timestamps as ISO-8601 strings</h2>
<p>Not epoch integers. They sort lexicographically, they are unambiguous about timezone, and
when you are staring at the D1 console at 2am trying to work out why a scheduled post did
not go out, you can read them.</p>
<h2 id="set-publishedat-exactly-once">Set <code>published_at</code> exactly once</h2>
<p>Editing a published post touches <code>updated_at</code> and nothing else. Unpublishing and
republishing does not reset it either. Otherwise a typo fix silently moves a two-year-old
post to the top of the feed and into every subscriber&#39;s reader.</p>
<h2 id="the-scheduled-publish-query-is-free">The scheduled-publish query is free</h2>
<pre><code class="language-sql">CREATE INDEX idx_posts_scheduled ON posts(status, scheduled_for)
  WHERE status = &#39;scheduled&#39;;</code></pre>
<p>A partial index over the handful of scheduled rows. The cron trigger runs every five
minutes and the query touches almost nothing.</p>
<h2 id="what-surprised-me">What surprised me</h2>
<p>Full-text search. <code>fts5</code> is available and works, but keeping the external-content table
in sync through triggers is more machinery than a personal blog needs. <code>LIKE</code> over title
and excerpt is genuinely fine below a few thousand posts, and you can add FTS the day
that stops being true.</p>', 'published', 'public', 'a2', NULL, NULL, 291, 2, '2026-07-06T16:40:00Z', '2026-07-06T16:40:00Z', '2026-07-04T08:15:00Z', NULL);
INSERT OR IGNORE INTO post_tags (post_id, tag_id) VALUES ('p3', 'd1');
INSERT OR IGNORE INTO post_tags (post_id, tag_id) VALUES ('p3', 'cloudflare');
INSERT OR IGNORE INTO post_tags (post_id, tag_id) VALUES ('p3', 'architecture');

INSERT OR IGNORE INTO posts (id, slug, title, subtitle, excerpt, body_md, body_html, status, visibility, author_id, cover_key, cover_alt, word_count, reading_minutes, created_at, updated_at, published_at, scheduled_for) VALUES ('p4', 'caching-a-blog-you-can-publish-to-instantly', 'Caching a blog you can publish to instantly', 'Long TTLs, aggressive purges, and a backstop for when purges fail', 'The two things a blog owner wants from caching are in direct tension: pages should be served from the edge without touching the database, and hitting Publish should make the post appear…', 'The two things a blog owner wants from caching are in direct tension: pages
should be served from the edge without touching the database, and hitting *Publish*
should make the post appear immediately.

## The policy

| Response | Cache-Control |
| --- | --- |
| Public HTML | `public, max-age=60, s-maxage=3600, stale-while-revalidate=86400` |
| Public JSON | `public, max-age=30, s-maxage=300` |
| `/media/*` | `public, max-age=31536000, immutable` |
| Admin | `private, no-store` |

Media gets a year because media keys contain a hash of the content. An object at a given
key is *the same bytes forever*; a new image is a new key. That is the whole trick — you
never have to invalidate media, you only have to stop referencing it.

## Purge on every mutation

Publishing purges the permalink, the home page, the archive, every affected tag page and
the feed. The important part is not the purge itself, it is that **every path to
publication goes through one function**:

```js
async function publishPost(env, ctx, post) {
  await writePublishState(env, post);
  await audit(env, ''post.publish'', post.id);
  ctx.waitUntil(purgeForPost(env, post));
}
```

The API endpoint calls it. The cron trigger for scheduled posts calls it. The MCP tool
calls it. There is exactly one place to forget a purge, so it does not get forgotten in
the path you use least.

## Assume the purge fails

Purges run in `waitUntil` and are best-effort. `s-maxage=3600` looks like it undermines
this, but it is the backstop: if a purge fails, the worst case is an hour of staleness,
not permanent staleness. Designing the failure mode to be *slow* rather than *wrong* is
worth more than making the happy path a few milliseconds faster.', '<p>The two things a blog owner wants from caching are in direct tension: pages
should be served from the edge without touching the database, and hitting <em>Publish</em>
should make the post appear immediately.</p>
<h2 id="the-policy">The policy</h2>
<table><thead><tr><th>Response</th><th>Cache-Control</th></tr></thead><tbody><tr><td>Public HTML</td><td><code>public, max-age=60, s-maxage=3600, stale-while-revalidate=86400</code></td></tr><tr><td>Public JSON</td><td><code>public, max-age=30, s-maxage=300</code></td></tr><tr><td><code>/media/*</code></td><td><code>public, max-age=31536000, immutable</code></td></tr><tr><td>Admin</td><td><code>private, no-store</code></td></tr></tbody></table>
<p>Media gets a year because media keys contain a hash of the content. An object at a given
key is <em>the same bytes forever</em>; a new image is a new key. That is the whole trick — you
never have to invalidate media, you only have to stop referencing it.</p>
<h2 id="purge-on-every-mutation">Purge on every mutation</h2>
<p>Publishing purges the permalink, the home page, the archive, every affected tag page and
the feed. The important part is not the purge itself, it is that <strong>every path to
publication goes through one function</strong>:</p>
<pre><code class="language-js">async function publishPost(env, ctx, post) {
  await writePublishState(env, post);
  await audit(env, &#39;post.publish&#39;, post.id);
  ctx.waitUntil(purgeForPost(env, post));
}</code></pre>
<p>The API endpoint calls it. The cron trigger for scheduled posts calls it. The MCP tool
calls it. There is exactly one place to forget a purge, so it does not get forgotten in
the path you use least.</p>
<h2 id="assume-the-purge-fails">Assume the purge fails</h2>
<p>Purges run in <code>waitUntil</code> and are best-effort. <code>s-maxage=3600</code> looks like it undermines
this, but it is the backstop: if a purge fails, the worst case is an hour of staleness,
not permanent staleness. Designing the failure mode to be <em>slow</em> rather than <em>wrong</em> is
worth more than making the happy path a few milliseconds faster.</p>', 'published', 'public', 'a1', NULL, NULL, 247, 2, '2026-06-27T10:00:00Z', '2026-06-27T10:00:00Z', '2026-06-27T10:00:00Z', NULL);
INSERT OR IGNORE INTO post_tags (post_id, tag_id) VALUES ('p4', 'performance');
INSERT OR IGNORE INTO post_tags (post_id, tag_id) VALUES ('p4', 'cloudflare');
INSERT OR IGNORE INTO post_tags (post_id, tag_id) VALUES ('p4', 'workers');

INSERT OR IGNORE INTO posts (id, slug, title, subtitle, excerpt, body_md, body_html, status, visibility, author_id, cover_key, cover_alt, word_count, reading_minutes, created_at, updated_at, published_at, scheduled_for) VALUES ('p5', 'the-editor-is-a-textarea', 'The editor is a textarea, and that is the point', 'Why the writing surface stayed boring', 'There is a strong pull toward building a rich-text editor. Contenteditable, floating toolbars, drag-to-reorder blocks. We built a textarea with a live preview beside it. The argument that…', 'There is a strong pull toward building a rich-text editor. Contenteditable,
floating toolbars, drag-to-reorder blocks. We built a textarea with a live preview beside
it.

## The argument that settled it

The blog has two kinds of author: people and models. A rich-text editor optimises for one
and actively harms the other.

A model editing a rich-text document model has to reason about a nested JSON tree, produce
a valid patch against it, and get node identity right. A model editing Markdown produces
text. One of these is reliable today and one is not, and since the MCP surface is a
headline feature rather than an afterthought, the format that both audiences handle well
wins.

## What we spent the effort on instead

- **Live preview** rendered with the same code the server will use at write time, so what
  you see is what gets stored.
- **Autosave** every 90 seconds into the revision table, with a visible saved-state
  indicator. Never a spinner over the text.
- **Slug locking.** The slug tracks the title until you edit it, then it stops. Renaming a
  published post never silently breaks its URL.
- **Conflict detection.** Saving sends `If-Match`. If someone else changed the post, you
  get a prompt, not a silent overwrite of their work.
- **Keyboard shortcuts** for bold, italic, link, and save.

None of that is exciting. All of it is the difference between an editor you tolerate and
one you stop noticing, which is the highest compliment an editor can earn.', '<p>There is a strong pull toward building a rich-text editor. Contenteditable,
floating toolbars, drag-to-reorder blocks. We built a textarea with a live preview beside
it.</p>
<h2 id="the-argument-that-settled-it">The argument that settled it</h2>
<p>The blog has two kinds of author: people and models. A rich-text editor optimises for one
and actively harms the other.</p>
<p>A model editing a rich-text document model has to reason about a nested JSON tree, produce
a valid patch against it, and get node identity right. A model editing Markdown produces
text. One of these is reliable today and one is not, and since the MCP surface is a
headline feature rather than an afterthought, the format that both audiences handle well
wins.</p>
<h2 id="what-we-spent-the-effort-on-instead">What we spent the effort on instead</h2>
<ul><li><strong>Live preview</strong> rendered with the same code the server will use at write time, so what
you see is what gets stored.</li><li><strong>Autosave</strong> every 90 seconds into the revision table, with a visible saved-state
indicator. Never a spinner over the text.</li><li><strong>Slug locking.</strong> The slug tracks the title until you edit it, then it stops. Renaming a
published post never silently breaks its URL.</li><li><strong>Conflict detection.</strong> Saving sends <code>If-Match</code>. If someone else changed the post, you
get a prompt, not a silent overwrite of their work.</li><li><strong>Keyboard shortcuts</strong> for bold, italic, link, and save.</li></ul>
<p>None of that is exciting. All of it is the difference between an editor you tolerate and
one you stop noticing, which is the highest compliment an editor can earn.</p>', 'published', 'public', 'a2', NULL, NULL, 245, 2, '2026-06-19T13:20:00Z', '2026-06-19T13:20:00Z', '2026-06-19T13:20:00Z', NULL);
INSERT OR IGNORE INTO post_tags (post_id, tag_id) VALUES ('p5', 'design');
INSERT OR IGNORE INTO post_tags (post_id, tag_id) VALUES ('p5', 'mcp');

INSERT OR IGNORE INTO posts (id, slug, title, subtitle, excerpt, body_md, body_html, status, visibility, author_id, cover_key, cover_alt, word_count, reading_minutes, created_at, updated_at, published_at, scheduled_for) VALUES ('p8', 'why-no-framework', 'Why there is no framework here', 'A defensible position, not a religious one', 'This site is HTML, CSS and ES modules. No build step, no bundler, no dependency tree. That is a choice with real costs, so here is the reasoning. What the constraint buys The deployed…', 'This site is HTML, CSS and ES modules. No build step, no bundler, no
dependency tree. That is a choice with real costs, so here is the reasoning.

## What the constraint buys

**The deployed artifact is the source.** What is in the repository is what is on the edge.
No sourcemaps, no "works locally, breaks in prod because of a transform".

**There is no supply chain.** A blog engine that can publish to the open internet, with an
MCP endpoint an agent can drive, has an attack surface worth keeping small. Zero
dependencies is zero dependencies to audit and zero to patch at 3am.

**It will still build in five years.** No build step cannot break.

## What it costs

Reactivity, mostly. There is no template layer, so every view is imperative DOM
construction, and that is more verbose. Some of it is genuinely tedious:

```js
const title = document.createElement(''h2'');
title.className = ''post-card__title'';
const link = document.createElement(''a'');
link.href = `/posts/${post.slug}`;
link.textContent = post.title;
title.append(link);
```

Three lines where a template would be one. The upside is that `textContent` makes
injection structurally impossible in the default path, which for a system that renders
user-authored content is worth some verbosity.

## Where the line is

If this grew a collaborative editor with real-time cursors, a framework would earn its
place and I would add one. It has a post list, an editor and a settings page. The
complexity does not justify the machinery yet, and "yet" is doing honest work in that
sentence.', '<p>This site is HTML, CSS and ES modules. No build step, no bundler, no
dependency tree. That is a choice with real costs, so here is the reasoning.</p>
<h2 id="what-the-constraint-buys">What the constraint buys</h2>
<p><strong>The deployed artifact is the source.</strong> What is in the repository is what is on the edge.
No sourcemaps, no &quot;works locally, breaks in prod because of a transform&quot;.</p>
<p><strong>There is no supply chain.</strong> A blog engine that can publish to the open internet, with an
MCP endpoint an agent can drive, has an attack surface worth keeping small. Zero
dependencies is zero dependencies to audit and zero to patch at 3am.</p>
<p><strong>It will still build in five years.</strong> No build step cannot break.</p>
<h2 id="what-it-costs">What it costs</h2>
<p>Reactivity, mostly. There is no template layer, so every view is imperative DOM
construction, and that is more verbose. Some of it is genuinely tedious:</p>
<pre><code class="language-js">const title = document.createElement(&#39;h2&#39;);
title.className = &#39;post-card__title&#39;;
const link = document.createElement(&#39;a&#39;);
link.href = `/posts/${post.slug}`;
link.textContent = post.title;
title.append(link);</code></pre>
<p>Three lines where a template would be one. The upside is that <code>textContent</code> makes
injection structurally impossible in the default path, which for a system that renders
user-authored content is worth some verbosity.</p>
<h2 id="where-the-line-is">Where the line is</h2>
<p>If this grew a collaborative editor with real-time cursors, a framework would earn its
place and I would add one. It has a post list, an editor and a settings page. The
complexity does not justify the machinery yet, and &quot;yet&quot; is doing honest work in that
sentence.</p>', 'published', 'public', 'a1', NULL, NULL, 228, 2, '2026-05-30T11:00:00Z', '2026-05-30T11:00:00Z', '2026-05-30T11:00:00Z', NULL);
INSERT OR IGNORE INTO post_tags (post_id, tag_id) VALUES ('p8', 'design');
INSERT OR IGNORE INTO post_tags (post_id, tag_id) VALUES ('p8', 'performance');

INSERT OR IGNORE INTO settings (key, value, updated_at) VALUES ('site_title', '"The add-blog Journal"', '2026-07-26T18:01:44Z');
INSERT OR IGNORE INTO settings (key, value, updated_at) VALUES ('site_description', '"Notes on building a blog engine for Cloudflare Workers — routing, storage, caching, and giving agents a way in."', '2026-07-26T18:01:44Z');
INSERT OR IGNORE INTO settings (key, value, updated_at) VALUES ('site_url', '"https://blog.mysite.com"', '2026-07-26T18:01:44Z');
INSERT OR IGNORE INTO settings (key, value, updated_at) VALUES ('admin_url', '"https://blog-admin.mysite.com"', '2026-07-26T18:01:44Z');
INSERT OR IGNORE INTO settings (key, value, updated_at) VALUES ('base_path', '"/"', '2026-07-26T18:01:44Z');
INSERT OR IGNORE INTO settings (key, value, updated_at) VALUES ('timezone', '"Europe/London"', '2026-07-26T18:01:44Z');
INSERT OR IGNORE INTO settings (key, value, updated_at) VALUES ('posts_per_page', '10', '2026-07-26T18:01:44Z');
INSERT OR IGNORE INTO settings (key, value, updated_at) VALUES ('allow_raw_html', 'false', '2026-07-26T18:01:44Z');
INSERT OR IGNORE INTO settings (key, value, updated_at) VALUES ('feed_full_content', 'false', '2026-07-26T18:01:44Z');
INSERT OR IGNORE INTO settings (key, value, updated_at) VALUES ('analytics_enabled', 'true', '2026-07-26T18:01:44Z');
INSERT OR IGNORE INTO settings (key, value, updated_at) VALUES ('social_image_key', 'null', '2026-07-26T18:01:44Z');
INSERT OR IGNORE INTO settings (key, value, updated_at) VALUES ('site_icon_key', 'null', '2026-07-26T18:01:44Z');
