/**
 * Generates migrations/seed.sql from assets/js/demo-data.js — the same
 * content that's been standing in for the API since Phase 1, now inserted
 * as real rows so the Phase 3 read path has something real to serve on
 * first deploy, and the front end shows the same content it always has
 * (no cover images or avatars, though: those are inline SVG data URIs in
 * demo mode, not real R2 objects, so seeded posts go out without one
 * rather than pointing at a media key nothing has uploaded).
 *
 * Not run automatically by anything — a deliberate, one-off step. Rerun it
 * by hand (`node scripts/generate-seed.mjs`) if demo-data.js ever changes
 * and the seed should reflect that.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { AUTHORS, TAGS, POSTS, SETTINGS } from '../assets/js/demo-data.js';
import { renderMarkdown } from '../assets/js/markdown.js';

const dirname = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.join(dirname, '..', 'migrations', 'seed.sql');

function sql(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return String(value);
  return `'${String(value).replace(/'/g, "''")}'`;
}

function nowIso() {
  return new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');
}

const createdAt = nowIso();
const lines = [
  '-- Generated by scripts/generate-seed.mjs from assets/js/demo-data.js.',
  '-- Do not hand-edit — rerun the generator instead.',
  '--',
  '-- Not applied automatically. Apply explicitly, once, after 0001_init.sql:',
  '--   npx wrangler d1 execute <db-name> --file=./migrations/seed.sql --remote',
  '',
];

for (const author of AUTHORS) {
  lines.push(
    `INSERT OR IGNORE INTO authors (id, email, name, bio, avatar_key, role, created_at) VALUES ` +
    `(${sql(author.id)}, ${sql(author.email)}, ${sql(author.name)}, ${sql(author.bio)}, NULL, ${sql(author.role)}, ${sql(createdAt)});`
  );
}
lines.push('');

for (const tag of TAGS) {
  lines.push(`INSERT OR IGNORE INTO tags (id, slug, name, description) VALUES (${sql(tag.slug)}, ${sql(tag.slug)}, ${sql(tag.name)}, NULL);`);
}
lines.push('');

// OR IGNORE throughout: this file is meant to be safe to apply more than
// once (a re-run against an already-seeded database is a no-op, not an
// error) — matters for local test runs (see src/test-setup.js) and for not
// punishing someone who re-runs the documented command by hand.
const published = POSTS.filter((post) => post.status === 'published');
for (const post of published) {
  const bodyHtml = renderMarkdown(post.body_md);
  lines.push(
    `INSERT OR IGNORE INTO posts (id, slug, title, subtitle, excerpt, body_md, body_html, status, visibility, ` +
    `author_id, cover_key, cover_alt, word_count, reading_minutes, created_at, updated_at, published_at, scheduled_for) VALUES (` +
    [
      sql(post.id), sql(post.slug), sql(post.title), sql(post.subtitle), sql(post.excerpt),
      sql(post.body_md), sql(bodyHtml), sql('published'), sql(post.visibility || 'public'),
      sql(post.author_id), 'NULL', 'NULL', sql(post.word_count), sql(post.reading_minutes),
      sql(post.created_at), sql(post.updated_at), sql(post.published_at), 'NULL',
    ].join(', ') + ');'
  );
  for (const tag of post.tags) {
    lines.push(`INSERT OR IGNORE INTO post_tags (post_id, tag_id) VALUES (${sql(post.id)}, ${sql(tag.slug)});`);
  }
  lines.push('');
}

for (const [key, value] of Object.entries(SETTINGS)) {
  lines.push(`INSERT OR IGNORE INTO settings (key, value, updated_at) VALUES (${sql(key)}, ${sql(JSON.stringify(value))}, ${sql(createdAt)});`);
}
lines.push('');

writeFileSync(outPath, lines.join('\n'));
console.log(`Wrote ${outPath} — ${AUTHORS.length} authors, ${TAGS.length} tags, ${published.length} posts, ${Object.keys(SETTINGS).length} settings.`);
